# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

llama-3-alpaca-it:
    model_name: simonycl/self-seq-Meta-Llama-3-8B-alpaca_it_llmam_70b
    endpoints:
        - api_base: http://0.0.0.0:8000
          api_key: token-abc123
    api_type: openai
    parallel: 8

llama-3-alpaca-sit:
    model_name: simonycl/self-seq-Meta-Llama-3-8B-alpaca_llmam_70b-iter-2
    endpoints:
        - api_base: http://0.0.0.0:8000
          api_key: token-abc123
    api_type: openai
    parallel: 8